// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.12.4
// source: proto/limiter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LimiterSync_SyncBuckets_FullMethodName = "/limiter.LimiterSync/SyncBuckets"
)

// LimiterSyncClient is the client API for LimiterSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LimiterSyncClient interface {
	// A stream of updates to keep network overhead low
	SyncBuckets(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BucketUpdate, SyncResponse], error)
}

type limiterSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewLimiterSyncClient(cc grpc.ClientConnInterface) LimiterSyncClient {
	return &limiterSyncClient{cc}
}

func (c *limiterSyncClient) SyncBuckets(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BucketUpdate, SyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LimiterSync_ServiceDesc.Streams[0], LimiterSync_SyncBuckets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BucketUpdate, SyncResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LimiterSync_SyncBucketsClient = grpc.ClientStreamingClient[BucketUpdate, SyncResponse]

// LimiterSyncServer is the server API for LimiterSync service.
// All implementations must embed UnimplementedLimiterSyncServer
// for forward compatibility.
type LimiterSyncServer interface {
	// A stream of updates to keep network overhead low
	SyncBuckets(grpc.ClientStreamingServer[BucketUpdate, SyncResponse]) error
	mustEmbedUnimplementedLimiterSyncServer()
}

// UnimplementedLimiterSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLimiterSyncServer struct{}

func (UnimplementedLimiterSyncServer) SyncBuckets(grpc.ClientStreamingServer[BucketUpdate, SyncResponse]) error {
	return status.Error(codes.Unimplemented, "method SyncBuckets not implemented")
}
func (UnimplementedLimiterSyncServer) mustEmbedUnimplementedLimiterSyncServer() {}
func (UnimplementedLimiterSyncServer) testEmbeddedByValue()                     {}

// UnsafeLimiterSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LimiterSyncServer will
// result in compilation errors.
type UnsafeLimiterSyncServer interface {
	mustEmbedUnimplementedLimiterSyncServer()
}

func RegisterLimiterSyncServer(s grpc.ServiceRegistrar, srv LimiterSyncServer) {
	// If the following call panics, it indicates UnimplementedLimiterSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LimiterSync_ServiceDesc, srv)
}

func _LimiterSync_SyncBuckets_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LimiterSyncServer).SyncBuckets(&grpc.GenericServerStream[BucketUpdate, SyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LimiterSync_SyncBucketsServer = grpc.ClientStreamingServer[BucketUpdate, SyncResponse]

// LimiterSync_ServiceDesc is the grpc.ServiceDesc for LimiterSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LimiterSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "limiter.LimiterSync",
	HandlerType: (*LimiterSyncServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncBuckets",
			Handler:       _LimiterSync_SyncBuckets_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/limiter.proto",
}
