// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: proto/limiter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BucketUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TotalCount    int64                  `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BucketUpdate) Reset() {
	*x = BucketUpdate{}
	mi := &file_proto_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BucketUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BucketUpdate) ProtoMessage() {}

func (x *BucketUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BucketUpdate.ProtoReflect.Descriptor instead.
func (*BucketUpdate) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{0}
}

func (x *BucketUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *BucketUpdate) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BucketUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BucketUpdate) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_proto_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_proto_limiter_proto protoreflect.FileDescriptor

const file_proto_limiter_proto_rawDesc = "" +
	"\n" +
	"\x13proto/limiter.proto\x12\alimiter\"\x7f\n" +
	"\fBucketUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x03R\n" +
	"totalCount\"2\n" +
	"\fSyncResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged2L\n" +
	"\vLimiterSync\x12=\n" +
	"\vSyncBuckets\x12\x15.limiter.BucketUpdate\x1a\x15.limiter.SyncResponse(\x01B\x14Z\x12rate-limiter/protob\x06proto3"

var (
	file_proto_limiter_proto_rawDescOnce sync.Once
	file_proto_limiter_proto_rawDescData []byte
)

func file_proto_limiter_proto_rawDescGZIP() []byte {
	file_proto_limiter_proto_rawDescOnce.Do(func() {
		file_proto_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_limiter_proto_rawDesc), len(file_proto_limiter_proto_rawDesc)))
	})
	return file_proto_limiter_proto_rawDescData
}

var file_proto_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_limiter_proto_goTypes = []any{
	(*BucketUpdate)(nil), // 0: limiter.BucketUpdate
	(*SyncResponse)(nil), // 1: limiter.SyncResponse
}
var file_proto_limiter_proto_depIdxs = []int32{
	0, // 0: limiter.LimiterSync.SyncBuckets:input_type -> limiter.BucketUpdate
	1, // 1: limiter.LimiterSync.SyncBuckets:output_type -> limiter.SyncResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_limiter_proto_init() }
func file_proto_limiter_proto_init() {
	if File_proto_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_limiter_proto_rawDesc), len(file_proto_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_limiter_proto_goTypes,
		DependencyIndexes: file_proto_limiter_proto_depIdxs,
		MessageInfos:      file_proto_limiter_proto_msgTypes,
	}.Build()
	File_proto_limiter_proto = out.File
	file_proto_limiter_proto_goTypes = nil
	file_proto_limiter_proto_depIdxs = nil
}
